connectedTo(kh, tc).
connectedTo(qp, kh).
connectedTo(de, cg).
connectedTo(ka, co).
connectedTo(yn, aq).
connectedTo(qp, ub).
connectedTo(cg, tb).
connectedTo(vc, aq).
connectedTo(tb, ka).
connectedTo(wh, tc).
connectedTo(yn, cg).
connectedTo(kh, ub).
connectedTo(ta, co).
connectedTo(de, co).
connectedTo(tc, td).
connectedTo(tb, wq).
connectedTo(wh, td).
connectedTo(ta, ka).
connectedTo(td, qp).
connectedTo(aq, cg).
connectedTo(wq, ub).
connectedTo(ub, vc).
connectedTo(de, ta).
connectedTo(wq, aq).
connectedTo(wq, vc).
connectedTo(wh, yn).
connectedTo(ka, de).
connectedTo(kh, ta).
connectedTo(co, tc).
connectedTo(wh, qp).
connectedTo(tb, vc).
connectedTo(td, yn).
