startsWithT(ts).
startsWithT(tq).
startsWithT(tw).
startsWithT(tg).
startsWithT(ts).
startsWithT(tm).
startsWithT(tv).
startsWithT(tx).
startsWithT(tm).
startsWithT(tx).
startsWithT(tt).
startsWithT(tq).
startsWithT(tg).
startsWithT(tm).
startsWithT(tk).
startsWithT(tz).
startsWithT(tx).
startsWithT(tk).
startsWithT(tg).
startsWithT(tk).
startsWithT(tk).
startsWithT(tq).
startsWithT(tv).
startsWithT(tw).
startsWithT(ta).
startsWithT(tb).
startsWithT(tm).
startsWithT(tp).
startsWithT(tw).
startsWithT(tb).
startsWithT(tm).
startsWithT(tp).
startsWithT(tb).
startsWithT(ta).
startsWithT(tx).
startsWithT(tw).
startsWithT(tf).
startsWithT(tc).
startsWithT(tq).
startsWithT(tz).
startsWithT(ts).
startsWithT(ts).
startsWithT(tf).
startsWithT(tf).
startsWithT(tb).
startsWithT(tz).
startsWithT(ta).
startsWithT(tc).
startsWithT(tq).
startsWithT(tf).
startsWithT(tp).
startsWithT(tc).
startsWithT(tb).
startsWithT(tp).
startsWithT(tf).
startsWithT(tw).
startsWithT(tb).
startsWithT(tq).
startsWithT(ta).
startsWithT(tv).
startsWithT(tb).
startsWithT(tv).
startsWithT(ts).
startsWithT(te).
startsWithT(tw).
startsWithT(tg).
startsWithT(tm).
startsWithT(ts).
startsWithT(tt).
startsWithT(tc).
startsWithT(ta).
startsWithT(te).
startsWithT(tz).
startsWithT(tv).
startsWithT(ts).
startsWithT(tt).
startsWithT(ts).
startsWithT(te).
startsWithT(tg).
startsWithT(ta).
startsWithT(tc).
startsWithT(tq).
startsWithT(ta).
startsWithT(tx).
startsWithT(tw).
startsWithT(te).
startsWithT(tf).
startsWithT(tf).
startsWithT(tv).
startsWithT(tw).
startsWithT(tw).
startsWithT(tc).
startsWithT(tx).
startsWithT(tv).
startsWithT(tx).
startsWithT(tb).
startsWithT(tm).
startsWithT(tw).
startsWithT(tm).
startsWithT(tp).
startsWithT(tv).
startsWithT(tw).
startsWithT(tg).
startsWithT(tq).
startsWithT(tp).
startsWithT(te).
startsWithT(tq).
startsWithT(tv).
startsWithT(tp).
startsWithT(tk).
startsWithT(tt).
startsWithT(tg).
startsWithT(tv).
startsWithT(tg).
startsWithT(ta).
startsWithT(tt).
startsWithT(tq).
startsWithT(tg).
startsWithT(ts).
startsWithT(tz).
startsWithT(tk).
startsWithT(tp).
startsWithT(tc).
startsWithT(te).
startsWithT(ta).
startsWithT(te).
startsWithT(tz).
startsWithT(tg).
startsWithT(tp).
startsWithT(tt).
startsWithT(tk).
startsWithT(te).
startsWithT(ts).
startsWithT(tx).
startsWithT(tx).
startsWithT(tw).
startsWithT(tp).
startsWithT(tg).
startsWithT(tq).
startsWithT(te).
startsWithT(tm).
startsWithT(tb).
startsWithT(tp).
startsWithT(tb).
startsWithT(tm).
startsWithT(tk).
startsWithT(tf).
startsWithT(tk).
startsWithT(tt).
startsWithT(tf).
startsWithT(tv).
startsWithT(tf).
startsWithT(tk).
startsWithT(tt).
startsWithT(tx).
startsWithT(tz).
startsWithT(tt).
startsWithT(tb).
startsWithT(te).
startsWithT(tc).
startsWithT(tz).
startsWithT(tq).
startsWithT(tx).
startsWithT(ta).
startsWithT(ts).
startsWithT(tt).
startsWithT(te).
startsWithT(ta).
startsWithT(tz).
startsWithT(tc).
startsWithT(ts).
startsWithT(tz).
startsWithT(tk).
startsWithT(tb).
startsWithT(tt).
startsWithT(tm).
startsWithT(tg).
startsWithT(tf).
startsWithT(tm).
startsWithT(tx).
startsWithT(tk).
startsWithT(tc).
startsWithT(tv).
startsWithT(tx).
startsWithT(tz).
startsWithT(te).
startsWithT(tq).
startsWithT(tw).
startsWithT(tp).
startsWithT(tz).
startsWithT(tt).
startsWithT(tb).
startsWithT(te).
startsWithT(tv).
startsWithT(ta).
startsWithT(ta).
startsWithT(ts).
startsWithT(tf).
startsWithT(tf).
startsWithT(tm).
startsWithT(tc).
startsWithT(tt).
startsWithT(tp).
startsWithT(tk).
startsWithT(tc).
startsWithT(tc).
